openapi: 3.0.0
info:
  title: Messages API
  version: 1.0.0
paths:
  /messages:
    get:
      summary: Get Messages
      description: Retrieves a list of messages.
      parameters:
        - name: status
          in: query
          description: Filter messages by status
          required: false
          schema:
            type: "string"
            enum:
              - "sent"
              - "read"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Message"
              example:
                messages:
                  - text: "Hello, World!"
                    status: "read"
                  - text: "How are you today?"
                    status: "sent"
                  - text: "Thanks, I'm fine. How about you?"
                    status: "sent"
        '400':
          description: "An error has occoured"
  /messages/send:
    post:
      summary: Send a Message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              required:
                - text
              properties:
                text:
                  description: The text you want to send
                  type: "string"
                  example: "Hello from Munich"
      responses:
        '204':
          description: Successfully sent
components:
  schemas:
    Message:
      type: object
      properties:
        messages:
          type: "array"
          items:
            type: "object"
            properties:
              uuid:
                type: "string"
              text:
                type: "string"
              status:
                type: "string"
                enum:
                  - "sent"
                  - "read"